#!/usr/bin/env bash
#
# setup_qlora_env.sh — QLoRA fine-tuning env for Gemma 4 12B on an MI300X (gfx942)
#
# Run this INSIDE an already-running AMD ROCm PyTorch environment
# (e.g. the rocm/pytorch container, or a host with ROCm + PyTorch installed).
# It does NOT install ROCm or PyTorch — it assumes the base is already present,
# exactly like `FROM rocm/pytorch:latest` did in the Containerfile.

set -euo pipefail

# ---------------------------------------------------------------------------
# 0. Configurable workspace (override with: WORKSPACE=/data/mike ./setup_qlora_env.sh)
# ---------------------------------------------------------------------------
WORKSPACE="${WORKSPACE:-/workspace}"
mkdir -p "$WORKSPACE"

echo "==> Using workspace: $WORKSPACE"

# ---------------------------------------------------------------------------
# 1. Environment variables (the Containerfile ENV block)
#    Written persistently, and exported for the current shell.
# ---------------------------------------------------------------------------
ENV_BLOCK=$(cat <<EOF
# --- QLoRA / MI300X env (generated by setup_qlora_env.sh) ---
export DEBIAN_FRONTEND=noninteractive
# Reduces allocator fragmentation. Not strictly needed on 192GB, but harmless.
# Set both keys: some ROCm PyTorch builds still read the CUDA-named var.
export PYTORCH_HIP_ALLOC_CONF=expandable_segments:True
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
# Keep HF cache on the mounted workspace so it survives restarts
export HF_HOME=$WORKSPACE/.cache/huggingface
# MI300X is gfx942 and natively supported by ROCm — no HSA_OVERRIDE needed.
export BNB_GPU_TARGETS=gfx942
EOF
)

PROFILE_TARGET="/etc/profile.d/qlora_env.sh"
if printf '%s\n' "$ENV_BLOCK" | tee "$PROFILE_TARGET" >/dev/null 2>&1; then
    echo "==> Wrote persistent env to $PROFILE_TARGET"
else
    PROFILE_TARGET="$HOME/.bashrc"
    printf '\n%s\n' "$ENV_BLOCK" >> "$PROFILE_TARGET"
    echo "==> No write access to /etc/profile.d; appended env to $PROFILE_TARGET"
fi

# Export into the current shell too, so the rest of this script uses them.
export DEBIAN_FRONTEND=noninteractive
export PYTORCH_HIP_ALLOC_CONF=expandable_segments:True
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export HF_HOME="$WORKSPACE/.cache/huggingface"
export BNB_GPU_TARGETS=gfx942
mkdir -p "$HF_HOME"

# ---------------------------------------------------------------------------
# 2. Training stack (arch-independent — identical to the Containerfile)
# ---------------------------------------------------------------------------
echo "==> Installing training stack..."
pip install --no-cache-dir \
    "transformers>=5.5.2" \
    "peft>=0.19.0" \
    "trl" \
    "accelerate" \
    "datasets" \
    "sentencepiece" \
    "protobuf" \
    "pillow"

# ---------------------------------------------------------------------------
# 3. bitsandbytes — gfx942 is covered by official ROCm wheels, so try the
#    wheel first. Fall back to a source build only if the import fails.
# ---------------------------------------------------------------------------
echo "==> Installing bitsandbytes (wheel first)..."
pip install --no-cache-dir "bitsandbytes>=0.49.0"

if ! python -c "import bitsandbytes" >/dev/null 2>&1; then
    echo "==> Wheel import failed; building bitsandbytes from source for gfx942..."
    pip install --no-cache-dir cmake ninja setuptools wheel
    BUILD_DIR="$(mktemp -d)"
    git clone --depth 1 --branch 0.49.2 \
        https://github.com/bitsandbytes-foundation/bitsandbytes.git "$BUILD_DIR/bitsandbytes"
    (
        cd "$BUILD_DIR/bitsandbytes"
        cmake -DCOMPUTE_BACKEND=hip -DBNB_ROCM_ARCH="gfx942" -S .
        make -j"$(nproc)"
        pip install --no-cache-dir .
    )
    rm -rf "$BUILD_DIR"
else
    echo "==> bitsandbytes wheel imports cleanly."
fi

# ---------------------------------------------------------------------------
# 4. GPU sanity-check script
# ---------------------------------------------------------------------------
echo "==> Writing /opt/sanity_check.py..."
SANITY_TARGET="/opt/sanity_check.py"
if ! : > "$SANITY_TARGET" 2>/dev/null; then
    SANITY_TARGET="$WORKSPACE/sanity_check.py"
    echo "==> No write access to /opt; using $SANITY_TARGET instead."
fi

cat > "$SANITY_TARGET" <<'PYEOF'
import torch, bitsandbytes as bnb
print("torch:", torch.__version__)
print("GPU available:", torch.cuda.is_available())
print("Device:", torch.cuda.get_device_name(0))
x = torch.randn(1024, 1024, device="cuda", dtype=torch.bfloat16)
print("bf16 matmul OK:", (x @ x).sum().item() is not None)
from bitsandbytes.nn import Linear4bit
l = Linear4bit(1024, 1024, compute_dtype=torch.bfloat16).cuda()
print("bnb NF4 forward OK:", l(x).shape)
PYEOF
echo "==> Sanity script at: $SANITY_TARGET"

# ---------------------------------------------------------------------------
# 5. llama.cpp for quantizing results (clone only, matching the Containerfile)
# ---------------------------------------------------------------------------
if [ -d "$WORKSPACE/llama.cpp" ]; then
    echo "==> llama.cpp already present, skipping clone."
else
    echo "==> Cloning llama.cpp into $WORKSPACE..."
    git clone https://github.com/ggml-org/llama.cpp.git "$WORKSPACE/llama.cpp"
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
cat <<EOF

============================================================
Setup complete.

Next steps:
  source $PROFILE_TARGET      # load env into your shell
  python $SANITY_TARGET       # verify GPU + bitsandbytes

Workspace: $WORKSPACE
============================================================
EOF
